# Generated by Django 5.1 on 2024-08-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(blank=True, max_length=64, null=True)),
                ('player2', models.CharField(blank=True, max_length=64, null=True)),
                ('player3', models.CharField(blank=True, max_length=64, null=True)),
                ('player4', models.CharField(blank=True, max_length=64, null=True)),
                ('score', models.IntegerField(default=1000)),
            ],
        ),
    ]
