# Generated by Django 3.2.8 on 2024-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_group_player1_alter_group_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
        ),
    ]
