# Generated by Django 5.1 on 2024-08-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_group_number1_group_number2_group_number3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='number2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='number3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='number4',
            field=models.FloatField(null=True),
        ),
    ]
